[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fig_viewer"
version = "0.1.0"
description = ""
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "redpigkiller" }
]

[project.urls]
